version: "3.8"

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
    - db=${db}
    - jwtPrivateKey=${jwtPrivateKey}
